common:
  status_queue: order_status

preparation:
  read_queue: placed_orders
  write_queue: prepared_orders
  delay_min: 1
  delay_max: 30
  logfile: log/preparation.log

delivery:
  read_queue: prepared_orders
  write_queue: 
  delay_min: 1
  delay_max: 30
  logfile: log/delivery.log
