common:
  status_queue: order_status

preparation:
  read_queue: placed_orders
  write_queue: prepared_orders
  started_status: in_preparation
  finished_status: prepared
  start_delay_min: 1
  start_delay_max: 5
  delay_min: 1
  delay_max: 30

delivery:
  read_queue: prepared_orders
  write_queue:
  started_status: in_delivery
  finished_status: delivered
  start_delay_min: 1
  start_delay_max: 5
  delay_min: 1
  delay_max: 30
